version: "3.0"
services:
  ydb:
    image: ydbplatform/local-ydb:latest
    hostname: localhost # for good discovery
    platform: linux/amd64
    environment:
      YDB_ANONYMOUS_CREDENTIALS: 1
    ports:
      - "2135:2135" # port with tls
      - "2136:2136" # port without tls
